export const LOGIN_WITH_OTP = "LOGIN_WITH_OTP";
export const LOGIN_WITH_OTP_SUCCESS = "LOGIN_WITH_OTP_SUCCESS";
export const LOGIN_WITH_OTP_ERROR = "LOGIN_WITH_OTP_ERROR";
export const SUBMIT_OTP = "SUBMIT_OTP";
export const SUBMIT_OTP_SUCCESS = "SUBMIT_OTP_SUCCESS";
export const SUBMIT_OTP_ERROR = "SUBMIT_OTP_ERROR";
