image: node:10.15.3

pipelines:
  custom: # Pipelines that can only be triggered manually
    staging:
      - step:
          name: app build
          script:
            - npm install
            - REACT_APP_ENVIRONMENT=staging npm run build:app
          artifacts:
            - packages/app/build/**
      - step:
          name: Deploy app to S3
          deployment: staging
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $STAGING_BUCKET_NAME
                ACL: "public-read"
                LOCAL_PATH: 'packages/app/build'
      - step:
          name: Invalidate Cloudfront Cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $STAGING_DISTRIBUTION_ID
      - step:
          name: admin build
          script:
            - npm install -g react-scripts
            - npm install
            - npm run build:admin
          artifacts:
            - packages/admin/build/**
      - step:
          name: Deploy admin to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $STAGING_ADMIN_BUCKET_NAME
                ACL: "public-read"
                LOCAL_PATH: 'packages/admin/build'
      - step:
          name: Invalidate admin Cloudfront Cache
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: $STAGING_ADMIN_DISTRIBUTION_ID
